# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='COMPANY',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('ssn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('age', models.IntegerField()),
                ('phone_num', models.CharField(max_length=20)),
                ('dno', models.IntegerField()),
            ],
        ),
    ]
