# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEPARTMENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=20)),
                ('dnumber', models.IntegerField()),
                ('mgr_ssn', models.IntegerField()),
                ('mgr_start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DEPENDENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essn', models.IntegerField()),
                ('department_name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('bdate', models.DateField()),
                ('relationship', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DEPF_LOCATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnumber', models.IntegerField()),
                ('dlocation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('minit', models.CharField(max_length=1)),
                ('lname', models.CharField(max_length=20)),
                ('bdate', models.DateField()),
                ('address', models.CharField(max_length=20)),
                ('ssn', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('salary', models.IntegerField()),
                ('super_ssn', models.IntegerField()),
                ('dno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PROJECT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pnumber', models.IntegerField()),
                ('plocation', models.CharField(max_length=20)),
                ('dnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WORKS_ON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essn', models.IntegerField()),
                ('pno', models.IntegerField()),
                ('hours', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='COMPANY',
        ),
    ]
