# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20171204_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bdate',
            field=models.CharField(max_length=20),
        ),
    ]
